name: Deploy Zola to Pages

on:
  push:
    branches:
      - main   # change to 'master' if that's your branch

jobs:
  build:
    name: Publish site
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'   # needed if your theme is a git submodule

      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.21.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
